config/routes.rb
Rails.application.routes.draw do
  
  root to: "sessions#new"

  get 'sessions/new'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

  resources :users do
  	resources :your_tips
  end

  

  resources :sessions
  
end

#               root GET    /                                            sessions#new
#       sessions_new GET    /sessions/new(.:format)                      sessions#new
#        users_index GET    /users/index(.:format)                       users#index
#         users_show GET    /users/show(.:format)                        users#show
#          users_new GET    /users/new(.:format)                         users#new
#         users_edit GET    /users/edit(.:format)                        users#edit
#     user_your_tips GET    /users/:user_id/your_tips(.:format)          your_tips#index
#                    POST   /users/:user_id/your_tips(.:format)          your_tips#create
#  new_user_your_tip GET    /users/:user_id/your_tips/new(.:format)      your_tips#new
# edit_user_your_tip GET    /users/:user_id/your_tips/:id/edit(.:format) your_tips#edit
#      user_your_tip GET    /users/:user_id/your_tips/:id(.:format)      your_tips#show
#                    PATCH  /users/:user_id/your_tips/:id(.:format)      your_tips#update
#                    PUT    /users/:user_id/your_tips/:id(.:format)      your_tips#update
#                    DELETE /users/:user_id/your_tips/:id(.:format)      your_tips#destroy
#              users GET    /users(.:format)                             users#index
#                    POST   /users(.:format)                             users#create
#           new_user GET    /users/new(.:format)                         users#new
#          edit_user GET    /users/:id/edit(.:format)                    users#edit
#               user GET    /users/:id(.:format)                         users#show
#                    PATCH  /users/:id(.:format)                         users#update
#                    PUT    /users/:id(.:format)                         users#update
#                    DELETE /users/:id(.:format)                         users#destroy
#           sessions GET    /sessions(.:format)                          sessions#index
#                    POST   /sessions(.:format)                          sessions#create
#        new_session GET    /sessions/new(.:format)                      sessions#new
#       edit_session GET    /sessions/:id/edit(.:format)                 sessions#edit
#            session GET    /sessions/:id(.:format)                      sessions#show
#                    PATCH  /sessions/:id(.:format)                      sessions#update
#                    PUT    /sessions/:id(.:format)                      sessions#update
#                    DELETE /sessions/:id(.:format)                      sessions#destroy

app/models/user.rb
class User < ActiveRecord::Base
	# using bcrypt by saying has_secure password
	has_secure_password

	has_many :your_tips

	def self.confirm(email_param, password_param)
	    user = User.find_by({email: email_param})
	    user.authenticate(password_param)
  	end
end

app/models/your_tip.rb
class YourTip < ActiveRecord::Base
	belongs_to :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user_params = params.require(:user)
  	user = User.confirm(user_params[:email], user_params[:password])
  	if user
      login(user)
  		redirect_to user_path(user.id)
  	else
      flash[:error] = "Failed To Authenticate. Please try again."
  		redirect_to sessions_new_path
  	end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  before_action :logged_in?, only: [:show]
  before_action :set_user

  def index
  end

  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)
    if @user.save
      login @user
      redirect_to sessions_new_path(@user.id)
    end
  end

  def edit
  end

  private

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/your_tips_controller.rb
class YourTipsController < ApplicationController
  # before_action :set_your_tip, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /your_tips
  # GET /your_tips.json
  def index
    @your_tips = YourTip.all
  end

  # GET /your_tips/1
  # GET /your_tips/1.json
  def show
  end

  # GET /your_tips/new
  # def new
  #   @your_tip = YourTip.new
  # end

  # GET /your_tips/1/edit
  def edit
  end

  # POST /your_tips
  # POST /your_tips.json
  def create
    @your_tip = @user.your_tips.create(your_tip_params) 
    redirect_to @user
  end

  # PATCH/PUT /your_tips/1
  # PATCH/PUT /your_tips/1.json
  # def update
  #   respond_to do |format|
  #     if @your_tip.update(your_tip_params)
  #       format.html { redirect_to @your_tip, notice: 'Your tip was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @your_tip }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @your_tip.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /your_tips/1
  # DELETE /your_tips/1.json
  # def destroy
  #   @your_tip.destroy
  #   respond_to do |format|
  #     format.html { redirect_to your_tips_url, notice: 'Your tip was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_your_tip
    #   @your_tip = YourTip.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def your_tip_params
      params.require(:your_tip).permit(:tip, :description)
    end

    def set_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end

	def logout
		@current_user = session[:user_id] = nil
	end

	def logged_in?
		if current_user == nil
			redirect_to "/login"
		end
	end

	def current_user
		@current_user = @current_user || User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/your_tips_helper.rb
module YourTipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoUEven</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1> New User </h1>
<p>Register form</p>

<%= form_for @user do |f| %>
	<div>
		<%= f.text_field :first_name, placeholder: "first name" %>
	</div>
	<div>
		<%= f.text_field :last_name, placeholder: "last name" %>
	</div>  
	<div>
		<%= f.text_field :email, placeholder: "Email" %>
	</div> 
	<div>
		<%= f.password_field :password, placeholder: "Password" %>
	</div> 
	<div>
		<%= f.password_field :password_confirmation, placeholder: "Password_confirmation" %>
	</div> 
	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome</h1>
<%= current_user.first_name %>!

	<div id="tips_wrapper">
		<%= render @user.your_tips %>
		
		<div id="form">
			<%= render "your_tips/form" %>
		</div>
	</div>

app/views/your_tips/_form.html.erb
<%= form_for([@user, @user.your_tips.build]) do |f| %>
  

  <div class="field">
    <%= f.label :tip %><br>
    <%= f.text_field :tip %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/your_tips/_your_tip.html.erb
<p> <strong>Tip:</strong> 
<%= your_tip.tip %>
</p> 
<p> <strong>Description:</strong> 
<%= your_tip.description %> 
</p> 

app/views/your_tips/edit.html.erb
<h1>Editing Your Tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @your_tip %> |
<%= link_to 'Back', your_tips_path %>

app/views/your_tips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Your Tips</h1>

<table>
  <thead>
    <tr>
      <th>Tip</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @your_tips.each do |your_tip| %>
      <tr>
        <td><%= your_tip.tip %></td>
        <td><%= your_tip.description %></td>
        <td><%= link_to 'Show', your_tip %></td>
        <td><%= link_to 'Edit', edit_your_tip_path(your_tip) %></td>
        <td><%= link_to 'Destroy', your_tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tip', new_your_tip_path %>

app/views/your_tips/new.html.erb
<h1>New Your Tip</h1>

<%= render 'form' %>

<%= link_to 'Back', your_tips_path %>

app/views/your_tips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tip:</strong>
  <%= @your_tip.tip %>
</p>

<p>
  <strong>Description:</strong>
  <%= @your_tip.description %>
</p>

<%= link_to 'Edit', edit_your_tip_path(@your_tip) %> |
<%= link_to 'Back', your_tips_path %>